# Generated by Django 2.2.5 on 2020-02-12 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.CharField(max_length=264, unique=True)),
                ('lName', models.CharField(max_length=264, unique=True)),
                ('Email', models.EmailField(max_length=264, unique=True)),
            ],
        ),
    ]
